name: "update-lecture"
auther: BieNew22
description: "update lecture information"
branding:
  icon: blue
  color: blue
runs:
  using: 'composite'
  steps:
    - name: Install Python3
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements.txt
    - name: run
      shell: bash
      run: python src/main.py
